holidays:
  fourth-of-july: true
  halloween: true
  christmas: true
  new-years-eve: true
  
  
events:
  join-fireworks: true
  join-message: true
  
messages:
  join-message: "&4&lHappy &f&l4th of &1&lJuly!"